/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AvailabilityAtResponse
 */
export interface AvailabilityAtResponse {
    /**
     * 
     * @type {Date}
     * @memberof AvailabilityAtResponse
     */
    timeId?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof AvailabilityAtResponse
     */
    isFree?: boolean;
}

/**
 * Check if a given object implements the AvailabilityAtResponse interface.
 */
export function instanceOfAvailabilityAtResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AvailabilityAtResponseFromJSON(json: any): AvailabilityAtResponse {
    return AvailabilityAtResponseFromJSONTyped(json, false);
}

export function AvailabilityAtResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvailabilityAtResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timeId': !exists(json, 'timeId') ? undefined : (new Date(json['timeId'])),
        'isFree': !exists(json, 'isFree') ? undefined : json['isFree'],
    };
}

export function AvailabilityAtResponseToJSON(value?: AvailabilityAtResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timeId': value.timeId === undefined ? undefined : (value.timeId.toISOString()),
        'isFree': value.isFree,
    };
}

