/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Building } from './Building';
import {
    BuildingFromJSON,
    BuildingFromJSONTyped,
    BuildingToJSON,
} from './Building';

/**
 * 
 * @export
 * @interface Room
 */
export interface Room {
    /**
     * 
     * @type {number}
     * @memberof Room
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Room
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof Room
     */
    floor?: number;
    /**
     * 
     * @type {Building}
     * @memberof Room
     */
    building?: Building;
    /**
     * 
     * @type {number}
     * @memberof Room
     */
    places?: number;
    /**
     * 
     * @type {string}
     * @memberof Room
     */
    roomType?: RoomRoomTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof Room
     */
    projector?: boolean;
}


/**
 * @export
 */
export const RoomRoomTypeEnum = {
    LectureRoom: 'LECTURE_ROOM',
    Workshop: 'WORKSHOP',
    ComputersRoom: 'COMPUTERS_ROOM',
    ChemistryLaboratory: 'CHEMISTRY_LABORATORY',
    Office: 'OFFICE'
} as const;
export type RoomRoomTypeEnum = typeof RoomRoomTypeEnum[keyof typeof RoomRoomTypeEnum];


/**
 * Check if a given object implements the Room interface.
 */
export function instanceOfRoom(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RoomFromJSON(json: any): Room {
    return RoomFromJSONTyped(json, false);
}

export function RoomFromJSONTyped(json: any, ignoreDiscriminator: boolean): Room {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'floor': !exists(json, 'floor') ? undefined : json['floor'],
        'building': !exists(json, 'building') ? undefined : BuildingFromJSON(json['building']),
        'places': !exists(json, 'places') ? undefined : json['places'],
        'roomType': !exists(json, 'roomType') ? undefined : json['roomType'],
        'projector': !exists(json, 'projector') ? undefined : json['projector'],
    };
}

export function RoomToJSON(value?: Room | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'number': value.number,
        'floor': value.floor,
        'building': BuildingToJSON(value.building),
        'places': value.places,
        'roomType': value.roomType,
        'projector': value.projector,
    };
}

